name: template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  # Networking
  dio: ^5.7.0

  flutter:
    sdk: flutter

  # Modules
  font_awesome_flutter: ^10.8.0
  gen:
    path: module/gen
  
  # Utilities
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  screenshot: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:
  uses-material-design: true
